"""
train.py
────────
Loads preprocessed data, builds the EEGPT model, and runs training.

Usage:
    python train.py

Requires:
    - data/processed_eeg.pt   (generated by preprocess.py)
    - EEGPT/checkpoint/eegpt_mcae_58chs_4s_large4E.ckpt
"""

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from pathlib import Path
from tqdm import tqdm

from preprocess import EEGDataset
from model import build_model

# ── Configuration ─────────────────────────────────────────────────────────────

DATA_PATH       = "processed_eeg.pt"
CHECKPOINT_PATH = "../EEGPT/checkpoint/eegpt_mcae_58chs_4s_large4E.ckpt"
SAVE_PATH       = "data/alzheimers_eegpt.pt"

NUM_CLASSES  = 2      # AD vs Control
BATCH_SIZE   = 32
NUM_EPOCHS   = 20
LEARNING_RATE= 1e-4


# ── Step 1: Load preprocessed data ───────────────────────────────────────────

print("Loading preprocessed data...")
data = torch.load(DATA_PATH)

X_train = data['X_train']   # (n_epochs, 19, 1024)
y_train = data['y_train']   # (n_epochs,)
X_val   = data['X_val']
y_val   = data['y_val']

print(f"Train: {len(X_train)} epochs | "
      f"AD={(y_train==0).sum()} | Control={(y_train==1).sum()}")
print(f"Val  : {len(X_val)}   epochs | "
      f"AD={(y_val==0).sum()} | Control={(y_val==1).sum()}\n")

# Wrap in Dataset and DataLoader
# shuffle=True for train so model sees different order each epoch
# shuffle=False for val so evaluation is consistent
train_loader = DataLoader(
    EEGDataset(X_train, y_train),
    batch_size=BATCH_SIZE,
    shuffle=True
)
val_loader = DataLoader(
    EEGDataset(X_val, y_val),
    batch_size=BATCH_SIZE,
    shuffle=False
)


# ── Step 2: Build model ───────────────────────────────────────────────────────

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}\n")

model = build_model(
    num_classes     = NUM_CLASSES,
    checkpoint_path = CHECKPOINT_PATH,
    device          = device
)


# ── Step 3: Loss and optimizer ────────────────────────────────────────────────

# CrossEntropyLoss is standard for classification
# If your classes are imbalanced, compute weights:
#   n_ad      = (y_train==0).sum().float()
#   n_control = (y_train==1).sum().float()
#   weights   = torch.tensor([1/n_ad, 1/n_control])
#   criterion = nn.CrossEntropyLoss(weight=weights.to(device))
criterion = nn.CrossEntropyLoss()

# filter() passes only unfrozen (trainable) parameters to the optimizer
# This ensures the frozen encoder weights are never updated
optimizer = torch.optim.Adam(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=LEARNING_RATE
)

# Learning rate scheduler: reduce LR by 50% if val loss stops improving
# Helps squeeze out extra performance in later epochs
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=3, verbose=True
)


# ── Step 4: Training and validation functions ─────────────────────────────────

def train_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss, total_correct, total = 0.0, 0, 0

    pbar = tqdm(loader, desc="  Training", leave=False,
                bar_format="{l_bar}{bar:30}{r_bar}")

    for x, y in pbar:
        x, y = x.to(device).float(), y.to(device)

        optimizer.zero_grad()
        logits = model(x)
        loss   = criterion(logits, y)
        loss.backward()
        optimizer.step()

        preds          = logits.argmax(dim=1)
        total_correct += (preds == y).sum().item()
        total_loss    += loss.item() * len(y)
        total         += len(y)

        # Live stats inside the progress bar
        pbar.set_postfix({
            'loss': f'{total_loss/total:.4f}',
            'acc':  f'{total_correct/total:.3f}'
        })

    return total_loss / total, total_correct / total


def val_epoch(model, loader, criterion, device):
    model.eval()
    total_loss, total_correct, total = 0.0, 0, 0

    pbar = tqdm(loader, desc="  Validating", leave=False,
                bar_format="{l_bar}{bar:30}{r_bar}")

    with torch.no_grad():
        for x, y in pbar:
            x, y   = x.to(device).float(), y.to(device)
            logits  = model(x)
            loss    = criterion(logits, y)

            preds          = logits.argmax(dim=1)
            total_correct += (preds == y).sum().item()
            total_loss    += loss.item() * len(y)
            total         += len(y)

            pbar.set_postfix({
                'loss': f'{total_loss/total:.4f}',
                'acc':  f'{total_correct/total:.3f}'
            })

    return total_loss / total, total_correct / total


# ── Step 5: Training loop ─────────────────────────────────────────────────────

print("─" * 65)
print(f"{'Epoch':>6} | {'Train Loss':>10} {'Train Acc':>10} | "
      f"{'Val Loss':>9} {'Val Acc':>9}")
print("─" * 65)

best_val_loss = float('inf')

for epoch in range(1, NUM_EPOCHS + 1):

    print(f"\nEpoch {epoch:02d}/{NUM_EPOCHS}")  # add this line
    
    train_loss, train_acc = train_epoch(
        model, train_loader, optimizer, criterion, device
    )
    val_loss, val_acc = val_epoch(
        model, val_loader, criterion, device
    )

    # Step the scheduler based on validation loss
    scheduler.step(val_loss)

    print(f"{epoch:>6} | {train_loss:>10.4f} {train_acc:>10.3f} | "
          f"{val_loss:>9.4f} {val_acc:>9.3f}")

    # Save the best model (lowest val loss)
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), SAVE_PATH)
        print(f"         ✓ Saved best model (val_loss={val_loss:.4f})")

print("─" * 65)
print(f"\nTraining complete. Best model saved to {SAVE_PATH}")
print(f"Best val loss: {best_val_loss:.4f}")
